#!/bin/sh

# Bail if fail2ban is not running
#--------------------------------

if [ ! -e /var/run/fail2ban/fail2ban.sock ]; then
    return 0
fi

# IPv4 only for now
#------------------

if [ "$FW_PROTO" != "ipv4" ]; then
    return 0
fi

# Regenerate iptables commands
#-----------------------------

JAILS=`LANG=en_US fail2ban-client status | grep "Jail list" | sed -e 's/.*Jail list://' -e 's/,//g'`

for JAIL in $JAILS; do
    echo "Processing $JAIL"

    ACTION=`fail2ban-client get $JAIL actions | tail -n 1`
    COMMAND=`fail2ban-client get $JAIL action $ACTION actionstart | grep "<iptables>"`
    # PROPERTIES=`fail2ban-client get $JAIL actionproperties $ACTION | sed -e 's/.*://' -e 's/,//g'`
    PROPERTIES="iptables chain name blocktype lockingopt protocol port"

    for PROPERTY in $PROPERTIES; do
        CHECK=`echo $PROPERTY | grep -v ^known | grep -v ^action`
        if [ -n "$CHECK" ]; then
            VALUE=`fail2ban-client get $JAIL action $ACTION $PROPERTY`
            VALUE_SED=`echo $VALUE |  sed 's/\//\\\\\//g'`
            COMMAND=`echo $COMMAND | sed "s/<$PROPERTY>/$VALUE_SED/"`
        fi
    done

    DELETE=`echo $COMMAND | sed 's/ -I / -D /'`

    $DELETE 2>/dev/null
    $COMMAND
done
